### ISSUE TITLE
运行报错：找不到application/Redis.class.php文件

### ISSUE THREAD

**Issue by goodwong** [tiyee/phpredismanage#1]
我将您的代码下载，放到我的ubuntu下面（php 7.0）运行，报错：
Unknown /home/vagrant/admin.pinzhu.com/public/PhpRedisManage-master/application/Redis.class.php is not found 53 lines of /home/vagrant/admin.pinzhu.com/public/PhpRedisManage-master/application/route.php [7.0.8-2+deb.sury.org~xenial+1(Linux)]

我在github上面也没找到这个文件，是哪里弄错了吗？

**Comment by tiyee** [comment]
你没有安装php的redis扩展

**Comment by tiyee** [comment]
你的php没有安装redis扩展
在 2017年1月17日，下午12:35，William Wong <notifications@github.com<mailto:notifications@github.com>> 写道：


我将您的代码下载，放到我的ubuntu下面（php 7.0）运行，报错：
Unknown /home/vagrant/admin.pinzhu.com/public/PhpRedisManage-master/application/Redis.class.php<http://admin.pinzhu.com/public/PhpRedisManage-master/application/Redis.class.php> is not found 53 lines of /home/vagrant/admin.pinzhu.com/public/PhpRedisManage-master/application/route.php<http://admin.pinzhu.com/public/PhpRedisManage-master/application/route.php> [7.0.8-2+deb.sury.org<http://deb.sury.org/>~xenial+1(Linux)]

我在github上面也没找到这个文件，是哪里弄错了吗？

**Comment by goodwong** [comment]
谢谢你，解决了
